import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // Every image on the site is currently an SVG illustration generated by
    // scripts/generate-images.mjs. Next special-cases .svg and serves it
    // straight from /public rather than through /_next/image; this routes it
    // back through the optimizer, which passes SVG along unchanged rather than
    // rasterising it.
    //
    // The two settings under it are Next's own defaults, written out because
    // they are what makes the "dangerously" bearable, and because a later
    // edit that drops them would otherwise look harmless. SVG is a document
    // format: it can carry <script> and can frame other pages. So the
    // optimizer serves it under a CSP that allows neither, and marks it as an
    // attachment, so a hand-authored file cannot be opened as a page on our
    // own origin.
    //
    // What actually keeps this safe is that no image here is user-supplied:
    // the files are generated in-repo and no remotePatterns are configured, so
    // the optimizer will not fetch a foreign SVG. Adding remotePatterns later
    // means revisiting this flag in the same commit.
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "script-src 'none'; frame-src 'none'; sandbox;",
    contentDispositionType: "attachment",
  },
};

export default nextConfig;
